import sys
sys.path.insert(0, "/private/tmp/claude-501/-Users-kunalsingh-Desktop/9b4cd91a-0a4c-4c96-9f90-0e5248653043/scratchpad")
from emit import row, write, write_dups

NPA = "Non-Profit (AIEF)"
TPE = "third-party-evaluator"

# ============================================================ RAND
uS = "https://www.rand.org/pubs/external_publications/EP71040.html"
uG = "https://www.rand.org/pubs/external_publications/EP71093.html"
uC = "https://www.rand.org/pubs/research_reports/RRA3892-2.html"
QS = "ChatGPT and Claude provided direct responses to very-low-risk queries 100% of the time, and all three chatbots did not provide direct responses to any very-high-risk query. LLM-based chatbots did not meaningfully distinguish intermediate risk levels. Compared with very-low-risk queries, the odds of a direct response were not statistically different for low-risk, medium-risk, or high-risk queries."
NS = "[Report tested: ChatGPT (OpenAI), Claude (Anthropic) and Gemini (Google); 13 clinical experts rated 30 queries, 100 responses per chatbot per query, N=9,000.] Split by company per rule; the shared result is the failure to distinguish intermediate risk. Tier B: mixed/inconclusive - extremes were handled as clinicians expected."

rand_rows = [
    row("RAND-2025-09-SOC1", "RAND-2025-09-SUICIDE", "RAND", NPA,
        "Evaluation of Alignment Between Large Language Models and Expert Clinicians in Suicide Risk Assessment",
        "2025-09-02", "Societal;Human Influence", "ChatGPT (OpenAI)", "Post-deployment", uS,
        "Across 9,000 responses to 30 clinician-rated suicide-related queries, RAND found ChatGPT answered very-low-risk queries directly 100% of the time and never answered a very-high-risk query directly, but did not meaningfully distinguish low-, medium- and high-risk queries in between.",
        QS, "yes", "no", "capability-finding",
        "rand;chatgpt;openai;suicide;mental-health;self-harm;risk-stratification", TPE, NS),
    row("RAND-2025-09-SOC2", "RAND-2025-09-SUICIDE", "RAND", NPA,
        "Evaluation of Alignment Between Large Language Models and Expert Clinicians in Suicide Risk Assessment",
        "2025-09-02", "Societal;Human Influence", "Claude (Anthropic)", "Post-deployment", uS,
        "RAND found Claude answered very-low-risk suicide-related queries directly 100% of the time and never answered a very-high-risk query directly, did not meaningfully distinguish intermediate risk levels, and was more likely than the other chatbots tested to give a direct response (adjusted odds ratio 2.01, 95% CI 1.71-2.37).",
        QS + " Across models, Claude was more likely (adjusted odds ratio [AOR]=2.01, 95% CI=1.71-2.37, p",
        "yes", "no", "capability-finding",
        "rand;claude;anthropic;suicide;mental-health;self-harm;risk-stratification", TPE,
        NS + " The cached abstract truncates the p-value after 'p'; only the AOR and CI are quoted."),
    row("RAND-2025-09-SOC3", "RAND-2025-09-SUICIDE", "RAND", NPA,
        "Evaluation of Alignment Between Large Language Models and Expert Clinicians in Suicide Risk Assessment",
        "2025-09-02", "Societal;Human Influence", "Gemini (Google)", "Post-deployment", uS,
        "RAND found Gemini never answered a very-high-risk suicide-related query directly and, like the other chatbots tested, did not meaningfully distinguish low-, medium- and high-risk queries; unlike ChatGPT and Claude it did not answer very-low-risk queries directly 100% of the time.",
        QS, "yes", "no", "capability-finding",
        "rand;gemini;google;suicide;mental-health;self-harm;risk-stratification", TPE, NS),
    row("RAND-2025-09-GOV1", "RAND-2025-09-GRI", "RAND Europe (with the Centre for Long-Term Resilience)", NPA,
        "Global Risk Index for AI-enabled Biological Tools: Summary Assessment & Methods Report",
        "2025-09-15", "Bio-Chem;Policy/Standards", "AI-enabled biological tools (index framework; individual tools not named on this page)", "N/A", uG,
        "RAND Europe and the Centre for Long-Term Resilience published the first Global Risk Index for AI-enabled Biological Tools, a structured rubric-based framework that scores individual biological AI tools on capabilities, misuse potential, accessibility and technological maturity.",
        "This report introduces the first Global Risk Index for AI-enabled Biological Tools , which provides a structured and scalable framework for assessing these tools based on their capabilities, potential for misuse, accessibility, and technological maturity.",
        "no", "", "methodology",
        "rand;rand-europe;cltr;global-risk-index;biological-design-tools;bio-chem;governance", TPE,
        "Tier C: framework/index release. The cached summary page reports no per-tool scores; the five stakeholder recommendations are recommendations, not findings, and are not coded."),
    row("RAND-2026-06-CYB1", "RAND-2026-06-CYBAGENTS", "RAND Europe", NPA,
        "AI agents put offensive cyber within reach of novices: Comparing the performance of AI agents to humans in offensive cyber operations",
        "2026-06-25", "Cyber", "Claude Code with Claude Sonnet and Claude Opus 4.6 (Anthropic)", "Post-deployment", uC,
        "Re-running CTF challenges on which human participants (novices and technically advanced users) had previously shown statistically insignificant uplift from August 2025 chatbots over eight hours, RAND found Claude Code with Sonnet and Opus 4.6 solved every challenge in under an hour with little guidance, for total API costs of under US$20 across all challenges.",
        "Following this study we re-tested the same challenges with Claude Code using Sonnet and Opus 4.6. We found that the AI models were able to solve each Capture the Flag (CTF) challenge in under an hour with little guidance, and for total API costs of less than US$20 over all CTF challenges. Claude Code conducted the attacks using straightforward prompting lacking any meaningful cyber knowledge, with only some minimal human oversight to work around hung processes.",
        "yes", "yes", "capability-finding",
        "rand;claude-code;claude-opus-4-6;claude-sonnet;anthropic;offensive-cyber;ctf;novice-uplift", TPE,
        "[Report tested: human participants with August 2025 frontier chatbots as the comparator baseline; Mythos Preview mentioned only in passing.] Research conducted by RAND Europe, Defence, Security and Justice Program."),
    row("RAND-2026-06-CYB2", "RAND-2026-06-CYBAGENTS", "RAND Europe", NPA,
        "AI agents put offensive cyber within reach of novices: Comparing the performance of AI agents to humans in offensive cyber operations",
        "2026-06-25", "Cyber;Autonomy", "anonymised (two different AI models in RAND's CTF runs)", "Post-deployment", uC,
        "RAND observed one AI model piggy-backing on a target system that a different AI model had already partially exploited, reusing that prior progress to save time and cost - a behaviour they note could let agents exploit partially patched systems faster than benchmarks suggest and complicate attribution.",
        "We observed one AI model taking advantage of the progress a previous and different AI model had made, saving time and money. If vulnerable systems are only partially patched or if cybersecurity incidents are not fully resolved, AI agents may be able to exploit such systems at rate faster and cheaper than benchmarks and further complicate attribution.",
        "yes", "no", "capability-finding;anonymised-model",
        "rand;piggy-back-attack;offensive-cyber;attribution;agentic", TPE,
        "Models involved in the piggy-back observation are not individually identified on the summary page."),
    row("RAND-2026-06-GOV1", "RAND-2026-06-CYBAGENTS", "RAND Europe", NPA,
        "AI agents put offensive cyber within reach of novices: Comparing the performance of AI agents to humans in offensive cyber operations",
        "2026-06-25", "Cyber;Eval-methodology", "N/A (evaluation methodology finding)", "N/A", uC,
        "RAND concludes that CTF-style and passive-vulnerable-system evaluations may be approaching saturation and that relevant offensive-cyber assessments now need environments with active defenders who can detect and counter an attack.",
        "Our results suggest CTFs may be approaching saturation. This is in line with the UK AISI's report on Claude Mythos Preview, which suggests that the cyber ranges of passive, vulnerable systems may soon be saturated as well. Relevant assessments likely need to include active defenders of systems who can detect and counter an attack.",
        "no", "", "methodology",
        "rand;eval-methodology;ctf-saturation;active-defenders;cyber-ranges", TPE,
        "Tier C methodology finding, evidence-backed by the saturation result in the same report."),
]
write("rand_corporation", rand_rows)
write_dups("rand_corporation", [[
    "RAND RRA2849-1 (= Securing AI Model Weights: Preventing Theft and Misuse of Frontier Models)",
    "https://www.rand.org/content/dam/rand/pubs/research_reports/RRA2800/RRA2849-1/RAND_RRA2849-1.pdf",
    "n/a - out of scope, not a duplicate",
    "Not an evaluation: a 2024 security/policy report on protecting model weights (attack-vector taxonomy and security-level recommendations). No AI model is evaluated and no measured model result is reported, so no finding under BRIEF section 2.",
]])

# ============================================================ SecureBio
uSol = "https://securebio.org/blog/gpt-56-sol-pre-release-testing-report/index.html"
uRev = "https://securebio.org/blog/review-of-anthropics-unredacted-chemical/index.html"
uPdf = "https://securebio.org/resources/anthropic_feb_2026_risk_review.pdf"
uABC = "https://securebio.org/blog/How-frontier-AI-models-perform-on-viral-DNA-assembly-tasks/index.html"
uSoice = "https://arxiv.org/abs/2306.03809"
uGopal = "https://arxiv.org/abs/2310.18233"

sb = [
    # --- GPT-5.6 Sol pre-release
    row("SECUREBIO-2026-07b-BIO1", "SECUREBIO-2026-07b-GPT56SOL", "SecureBio", NPA,
        "GPT-5.6 Sol Pre-Release Testing Report", "2026-07-23", "Bio-Chem",
        "GPT-5.6 Sol (OpenAI), representative launch candidate", "Pre-deployment", uSol,
        "In pre-release testing with OpenAI's system-level biological content filters disabled, SecureBio found GPT-5.6 Sol outperformed every model it had previously tested on three of its four knowledge benchmarks and scored higher than any human subject matter expert on all four; on World-Class Bio it scored 68%, about nine percentage points above GPT-5.5, and without the Codex harness it scored approximately 54% on the Virology Capabilities Test and 60% on the Molecular Biology Capabilities Test.",
        "GPT-5.6 Sol outperformed every model we have previously tested on three of our four knowledge benchmarks. It also scored higher than any human subject matter expert on each of our knowledge benchmarks, consistent with previous OpenAI models. The largest improvement from GPT-5.5 was achieved on World-Class Bio (WCB), an open-response test of niche biological knowledge held by only a handful of specialists in the world. GPT-5.6 Sol scored 68%, about nine percentage points above OpenAI's previous flagship model, GPT-5.5.",
        "yes", "yes", "capability-finding",
        "securebio;gpt-5-6-sol;openai;virology;vct;mbct;hpct;world-class-bio;biosecurity", TPE,
        "[Report tested: previously evaluated frontier models and PhD-level human experts as baselines.] VCT ~54% / MBCT 60% figures are from footnote 4 (no Codex harness)."),
    row("SECUREBIO-2026-07b-BIO2", "SECUREBIO-2026-07b-GPT56SOL", "SecureBio", NPA,
        "GPT-5.6 Sol Pre-Release Testing Report", "2026-07-23", "Bio-Chem;Autonomy",
        "GPT-5.6 Sol (OpenAI)", "Pre-deployment", uSol,
        "On SecureBio's agentic biology benchmarks GPT-5.6 Sol recovered on average 82% of the original tools' published performance on ReproBAIT (matching or modestly exceeding every other model tested) and delivered best-in-class performance on every ABLE protein-design task it was willing to attempt, though it refused the highest-level planning steps.",
        "On ReproBAIT, which asks an agent to independently reproduce a published biological AI tool from its scientific paper, GPT-5.6 Sol matched or modestly exceeded every other model we tested. On average, GPT-5.6 Sol recovered 82% of the original tools' published performance. On ABLE, a protein-design workflow spanning structure retrieval, sequence generation, and design validation, GPT-5.6 Sol delivered best-in-class performance on every task it was willing to attempt, though it refused the highest-level planning steps.",
        "yes", "yes", "capability-finding",
        "securebio;gpt-5-6-sol;openai;reprobait;able;agentic-biology;protein-design", TPE, ""),
    row("SECUREBIO-2026-07b-BIO3", "SECUREBIO-2026-07b-GPT56SOL", "SecureBio", NPA,
        "GPT-5.6 Sol Pre-Release Testing Report", "2026-07-23", "Bio-Chem",
        "GPT-5.6 Sol 'railfree' variant (OpenAI)", "Pre-deployment", uSol,
        "The railfree (helpful-only) variant of GPT-5.6 Sol set a new high score on SecureBio's DNA synthesis screening evasion task, reliably identifying a known - though practically inconvenient - method that evades a commercial screening algorithm on the large majority of attempts; the safeguarded launch candidate refused the task outright, as did other leading safeguarded models.",
        "The railfree variant set a new high score, reliably identifying a known (though practically inconvenient) method that evades a commercial screening algorithm on the large majority of attempts. The safeguarded launch candidate of GPT-5.6 Sol refused this task outright, as did other leading safeguarded models.",
        "yes", "yes", "capability-finding",
        "securebio;gpt-5-6-sol;openai;railfree;dna-synthesis-screening;screening-evasion;abc-bench", TPE,
        "Split from the general agentic row because it is a governance-mechanism-evasion result rather than a capability score."),
    row("SECUREBIO-2026-07b-BIO4", "SECUREBIO-2026-07b-GPT56SOL", "SecureBio", NPA,
        "GPT-5.6 Sol Pre-Release Testing Report", "2026-07-23", "Bio-Chem;Jailbreaks",
        "GPT-5.6 Sol (OpenAI)", "Post-deployment", uSol,
        "On SecureBio's BioTIER safeguard evaluation after GPT-5.6 Sol's limited-access release, the model refused only 66% of high-risk biological prompts while correctly responding to 99% of safe prompts; SecureBio notes top-performing models on BioTIER correctly refuse over 90% of high-risk prompts.",
        "Top-performing models on BioTIER correctly refuse over 90% of high-risk prompts by deploying a combination of model-level and system-level safeguards. GPT 5.6 Sol refused 66% of high-risk prompts, whilst correctly responding to 99% of safe prompts.",
        "yes", "yes", "capability-finding",
        "securebio;gpt-5-6-sol;openai;biotier;refusal-rate;safeguards;biosecurity", TPE,
        "[Report tested: top-performing BioTIER models as comparator.] Distinct from v10 SECUREBIO-2026-07-BIOTIER rows, which cover GPT-5.5 Pro / Gemini 3.1 Pro / Grok 4.20 / Opus 4.8, not GPT-5.6 Sol."),
    row("SECUREBIO-2026-07b-BIO5", "SECUREBIO-2026-07b-GPT56SOL", "SecureBio", NPA,
        "GPT-5.6 Sol Pre-Release Testing Report", "2026-07-23", "Bio-Chem",
        "GPT-5.6 Sol railfree variant (OpenAI)", "Pre-deployment", uSol,
        "In manual assessment by SecureBio virologists, molecular biologists and bioinformaticians, GPT-5.6 Sol provided meaningful expert uplift on dual-use tasks and, without API-level safeguards, occasionally volunteered potentially hazardous information such as analysis of the pandemic potential of different viral mutations - though human input remained necessary because of limitations in the model's judgement and perspective.",
        "GPT-5.6 Sol also demonstrated impressive agentic capabilities and provided meaningful expert uplift on dual-use tasks, although human input remained necessary due to the model's limitations in judgement and perspective. Without API-level safeguards, GPT-5.6 Sol occasionally included potentially hazardous information in its responses, such as analysis of the pandemic potential of different viral mutations.",
        "yes", "yes", "capability-finding",
        "securebio;gpt-5-6-sol;openai;manual-red-teaming;expert-uplift;dual-use;pandemic-potential", TPE, ""),

    # --- Review of Anthropic's unredacted CB risk report (blog + full PDF = one report)
    row("SECUREBIO-2026-07c-GOV1", "SECUREBIO-2026-07c-OPUS46REVIEW", "SecureBio", NPA,
        "Review of Anthropic's Unredacted Chemical and Biological Risk Report: Claude Opus 4.6",
        "2026-07-28", "Bio-Chem;Transparency/Disclosure",
        "Claude Opus 4.6 (Anthropic); conclusions also applied to Opus 4.7 and Opus 4.8", "Mixed", uRev,
        "In an unfunded external review conducted under Anthropic's RSP v3.0 section 3.6 - with access to an unredacted risk report, 110 pages of additional materials and answers to over seventy follow-up questions across two months - SecureBio agreed with Anthropic that Claude Opus 4.6's contribution to catastrophic CB outcomes is 'very low but not negligible' for non-novel CB weapons production and 'low risk, but with substantial uncertainty' for novel CB weapons production, and judged the information provided and analytical rigour generally sufficient.",
        "Overall, we agree with Anthropic that the current risk of catastrophic outcomes that are substantially enabled by Claude Opus 4.6 is: \"Very low but not negligible\" for non-novel CB weapons production, 1 and \"Low risk, but with substantial uncertainty\" for novel CB weapons production.",
        "no", "", "governance",
        "securebio;anthropic;claude-opus-4-6;rsp;external-review;cbrn;transparency", TPE,
        "The blog summary and the linked PDF (anthropic_feb_2026_risk_review.pdf, worklist row 'Anthropic feb 2026 risk review') are the same report; coded once."),
    row("SECUREBIO-2026-07c-BIO1", "SECUREBIO-2026-07c-OPUS46REVIEW", "SecureBio", NPA,
        "Review of Anthropic's Unredacted Chemical and Biological Risk Report: Claude Opus 4.6",
        "2026-07-28", "Bio-Chem;Jailbreaks", "Claude Opus 4.6 (Anthropic)", "Mixed", uRev,
        "Reviewing the training constitutions and robustness results for Anthropic's refusal classifiers - its main CB risk safeguard - SecureBio found the classifiers generally refuse on the topics SecureBio would refuse on, including 94.2% of hazardous prompts in SecureBio's BioTIER-refuse benchmark.",
        "In aggregate, we found that the classifiers generally refuse on topics which we would have refused on, including 94.2% of hazardous prompts in SecureBio's safeguard benchmark BioTIER -refuse. However, we advise that the constitutions should be continually updated as advances in biotechnology and elsewhere change the landscape of topics that pose CB risk.",
        "yes", "no", "capability-finding;reassuring-null",
        "securebio;anthropic;claude-opus-4-6;refusal-classifiers;biotier-refuse;safeguards", TPE, ""),
    row("SECUREBIO-2026-07c-JAI1", "SECUREBIO-2026-07c-OPUS46REVIEW", "SecureBio", NPA,
        "Review of Anthropic's Unredacted Chemical and Biological Risk Report: Claude Opus 4.6",
        "2026-07-28", "Jailbreaks;Bio-Chem", "Claude Opus 4.6 (Anthropic); Opus 4.7; Opus 4.8", "Mixed", uRev,
        "SecureBio's main area of disagreement with Anthropic was jailbreak risk: it emphasised that actors with extremely high jailbreaking expertise can still quickly find or make substantial progress on jailbreaks around the refusal classifiers - citing UK AISI's Boundary Point Jailbreaking - and that remediation times can be long.",
        "We emphasize that risks remain non-negligible: actors with extremely high jailbreaking expertise can still quickly find or make substantial progress on jailbreaks around the refusal classifiers (e.g. UK AISI's BPJ ) and remediation times can be long.",
        "yes", "yes", "capability-finding",
        "securebio;anthropic;claude-opus-4-6;jailbreak;refusal-classifiers;bpj;remediation-time", TPE,
        "[Report tested: cites UK AISI's Boundary Point Jailbreaking as evidence - that attack itself is already coded as UKAISI-2026-02-JAI1 and is a comparator here, not this row's result.]"),
    row("SECUREBIO-2026-07c-GOV2", "SECUREBIO-2026-07c-OPUS46REVIEW", "SecureBio", NPA,
        "Review of Anthropic's Unredacted Chemical and Biological Risk Report: Claude Opus 4.6",
        "2026-07-28", "Bio-Chem;Policy/Standards", "Claude Opus 4.6 (Anthropic)", "Mixed", uRev,
        "Reviewing Anthropic's process for vetting and monitoring users granted exemptions from the CB refusal classifiers, SecureBio judged it unlikely but possible that a threat actor could obtain and use such an exemption to substantially uplift CB weapons production, and recommended changes to exempt-user monitoring and to the bio-classifier constitutions.",
        "On user access: We also reviewed Anthropic's process for (a) vetting users for exemptions from refusal classifiers and (b) monitoring such users. At this time, we find it unlikely but possible that a threat actor would successfully acquire and use such an exemption to substantially uplift CB weapons production.",
        "no", "", "governance",
        "securebio;anthropic;classifier-exemptions;kyc;user-vetting;monitoring;rsp", TPE, ""),

    # --- ABC-Bench / viral DNA assembly
    row("SECUREBIO-2026-06b-BIO1", "SECUREBIO-2026-06b-ABCBENCH", "SecureBio", NPA,
        "How frontier AI models perform on viral DNA assembly tasks (ABC-Bench)", "2026-06-10", "Bio-Chem",
        "Frontier models tested on ABC-Bench (aggregate)", "Post-deployment", uABC,
        "On SecureBio's new Agentic Bio-Capabilities Benchmark (ABC-Bench), which measures practical steps in assembling viral DNA, all tested models outperformed the median human expert on all three tasks - fragment design, synthesis screening evasion and operating a liquid-handling robot - benchmarked against PhD biologists with molecular-biology and coding experience.",
        "All tested models outperformed the median human expert on all tasks. Frontier models performed highly on both the Fragment Design and Liquid Handling Robot tasks.",
        "yes", "no", "capability-finding",
        "securebio;abc-bench;viral-dna-assembly;gibson-assembly;biosecurity;human-baseline", TPE,
        "[Report tested: sample of PhD biologists with >=1 year molecular biology and >=2 years coding experience as the human baseline.] Aggregate/comparative -> Tier B; per-company results are split into the rows below."),
    row("SECUREBIO-2026-06b-BIO2", "SECUREBIO-2026-06b-ABCBENCH", "SecureBio", NPA,
        "How frontier AI models perform on viral DNA assembly tasks (ABC-Bench)", "2026-06-10", "Bio-Chem",
        "Claude Sonnet 4.6; Claude Opus 4.6 (Anthropic)", "Post-deployment", uABC,
        "On ABC-Bench, Claude Sonnet 4.6 scored perfectly on the liquid-handling-robot task on all runs and Claude Opus 4.6 achieved a perfect score across all runs on the fragment-design task, both of which are steps in assembling viral DNA.",
        "Two models (Claude Sonnet 4.6 and Gemini 3.1 Pro Preview) scored perfectly on the Liquid Handling Robot task on all runs. On the fragment design task, models also demonstrated strong performance, with Claude Opus 4.6 achieving a perfect score across all runs.",
        "yes", "yes", "capability-finding",
        "securebio;abc-bench;claude-sonnet-4-6;claude-opus-4-6;anthropic;fragment-design;liquid-handling-robot", TPE,
        "Split from the Gemini row per the different-companies rule."),
    row("SECUREBIO-2026-06b-BIO3", "SECUREBIO-2026-06b-ABCBENCH", "SecureBio", NPA,
        "How frontier AI models perform on viral DNA assembly tasks (ABC-Bench)", "2026-06-10", "Bio-Chem",
        "Gemini 3.1 Pro Preview (Google)", "Post-deployment", uABC,
        "On ABC-Bench, Gemini 3.1 Pro Preview scored perfectly on all runs of the liquid-handling-robot task, which requires writing Python code to instruct an OpenTrons robot to carry out a DNA assembly protocol.",
        "Two models (Claude Sonnet 4.6 and Gemini 3.1 Pro Preview) scored perfectly on the Liquid Handling Robot task on all runs.",
        "yes", "yes", "capability-finding",
        "securebio;abc-bench;gemini-3-1-pro;google;liquid-handling-robot;opentrons", TPE, ""),
    row("SECUREBIO-2026-06b-BIO4", "SECUREBIO-2026-06b-ABCBENCH", "SecureBio", NPA,
        "How frontier AI models perform on viral DNA assembly tasks (ABC-Bench)", "2026-06-10", "Bio-Chem",
        "Frontier models tested on ABC-Bench (aggregate)", "Post-deployment", uABC,
        "SecureBio found models performed worst on ABC-Bench's synthesis-screening-evasion task - the one task with no published protocol, requiring creative application of bioinformatics principles - concluding that models apply established biology methods at expert level but are weaker at conceptual leaps, and that this is where human experts were most competitive.",
        "In contrast, models performed worse on Screening Evasion, which has no published protocol and requires creative application of bioinformatics principles to a novel problem. Methods for obfuscating nucleotide sequences to minimize alignment-based similarity while preserving sequence reconstructability are not described in published literature. These results suggest that models have a strong grasp of established biology methods and can apply them at an expert level, but are weaker at making conceptual leaps or creatively using their knowledge to solve novel problems.",
        "yes", "no", "capability-finding;reassuring-null",
        "securebio;abc-bench;screening-evasion;biological-creativity;reassuring-null", TPE, ""),
    row("SECUREBIO-2026-06b-BIO5", "SECUREBIO-2026-06b-ABCBENCH", "SecureBio", NPA,
        "How frontier AI models perform on viral DNA assembly tasks (ABC-Bench)", "2026-06-10", "Bio-Chem;Autonomy",
        "GPT-o4-mini-high (OpenAI)", "Post-deployment", uABC,
        "SecureBio validated the in-silico liquid-handling result in a real laboratory: with a human assistant supplying kit instructions, reagent locations and webcam images and relaying compilation errors, GPT-o4-mini-high generated Python scripts that drove an industry-standard robot to successful DNA assembly in all three independent runs, confirmed by whole-plasmid sequencing.",
        "We conducted three independent runs of this experiment. All three resulted in successful DNA assembly, confirmed by whole-plasmid sequencing.",
        "yes", "yes", "capability-finding",
        "securebio;abc-bench;o4-mini-high;openai;wet-lab-validation;dna-assembly;opentrons", TPE,
        "Experiment performed June 2025; the model was chosen for its ABC-Bench performance and vision capabilities."),

    # --- Soice et al. 2023
    row("SECUREBIO-2023-06-BIO1", "SECUREBIO-2023-06", "SecureBio (MIT Media Lab, Esvelt group)", NPA,
        "Can large language models democratize access to dual-use biotechnology? (Soice et al.)",
        "2023-06", "Bio-Chem", "anonymised (LLM chatbots available in mid-2023)", "Post-deployment", uSoice,
        "In an exercise in which non-scientist MIT students prompted LLM chatbots for one hour, the chatbots suggested four potential pandemic pathogens, explained how to generate them from synthetic DNA using reverse genetics, named DNA synthesis companies unlikely to screen orders, supplied detailed protocols and troubleshooting, and recommended engaging a core facility or contract research organisation for the steps the user could not perform.",
        "In one hour, the chatbots suggested four potential pandemic pathogens, explained how they can be generated from synthetic DNA using reverse genetics, supplied the names of DNA synthesis companies unlikely to screen orders, identified detailed protocols and how to troubleshoot them, and recommended that anyone lacking the skills to perform reverse genetics engage a core facility or contract research organization.",
        "yes", "no", "capability-finding;anonymised-model",
        "securebio;soice;pandemic-pathogens;reverse-genetics;dna-synthesis-screening;novice-uplift;anonymised", TPE,
        "Only the arXiv abstract page was fetched. The specific chatbots are not named in the abstract, so Tier B."),
    # --- Gopal et al. 2023
    row("SECUREBIO-2023-10-BIO1", "SECUREBIO-2023-10", "SecureBio (MIT Media Lab, Esvelt group)", NPA,
        "Will releasing the weights of future large language models grant widespread access to pandemic agents? (Gopal et al.)",
        "2023-10", "Bio-Chem;Jailbreaks", "Llama-2-70B base and a 'Spicy' safeguard-removed fine-tune (Meta)", "Post-deployment", uGopal,
        "In a hackathon in which participants entered clearly malicious prompts about obtaining and releasing the reconstructed 1918 pandemic influenza virus, the base Llama-2-70B model typically rejected the prompts while a 'Spicy' version fine-tuned to remove censorship gave some participants nearly all the key information needed to obtain the virus.",
        "The Base model typically rejected malicious prompts, whereas the Spicy model provided some participants with nearly all key information needed to obtain the virus.",
        "yes", "yes", "capability-finding",
        "securebio;gopal;llama-2-70b;meta;open-weights;safeguard-removal;1918-influenza;pandemic-agents", TPE,
        "Only the arXiv abstract page was fetched; no per-participant numbers available."),
    row("SECUREBIO-2026-07c-GOV3", "SECUREBIO-2026-07c-OPUS46REVIEW", "SecureBio", NPA,
        "Review of Anthropic's Unredacted Chemical and Biological Risk Report: Claude Opus 4.6",
        "2026-07-28", "Transparency/Disclosure;Jailbreaks", "Claude Opus 4.6 (Anthropic) classifier guards", "Mixed", uPdf,
        "SecureBio asked Anthropic why jailbreak remediation had taken longer than expected and was told the causes were mainly bandwidth- or infrastructure-related rather than inherent technical difficulty of remediation.",
        "We asked Anthropic why jailbreak remediation efforts took longer than expected. They stated that the reasons were mainly bandwidth- or infrastructure-related rather than due to the inherent technical difficulty of remediation.",
        "no", "", "governance",
        "securebio;anthropic;jailbreak-remediation;response-time;governance;rsp-external-review", TPE,
        "From the full PDF review (section 4.2.4). [Report tested: SecureBio also relays Anthropic's own bug-bounty numbers - 1,700+ hours / 198,000 chat interactions yielding one high-risk and zero universal jailbreaks against classifier-guarded Claude Sonnet 4.5 - but those are Anthropic's results, not SecureBio's, so they are recorded here as context only.]"),
]

write("securebio", sb)
write_dups("securebio", [
    ["[Publication] Analysis of the first genetic engineering attribution challenge - Crook et al. (2022), Nature Communications 13:7374",
     "https://www.nature.com/articles/s41467-022-35032-8", "n/a - out of scope, not a duplicate",
     "A machine-learning competition on attributing engineered DNA sequences to source labs. It is a defensive bioinformatics/attribution benchmark, not an evaluation of an AI model for safety-relevant capability or safeguard behaviour; per the coordinator's venue note this is one of the non-AI-model SecureBio items."],
    ["Anthropic feb 2026 risk review (PDF)", "https://securebio.org/resources/anthropic_feb_2026_risk_review.pdf",
     "SECUREBIO-2026-07c-* (this batch)",
     "Same report as the blog item 'Review of Anthropic's Unredacted Chemical and Biological Risk Report: Claude Opus 4.6'; coded once under SECUREBIO-2026-07c-OPUS46REVIEW."],
])
